Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/ki18n': '@same'
    'frameworks/kconfig': '@same'

Options:
 test-before-installing: True
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
 enable-lsan: True
